name: UI
options:
  bundleIdPrefix: com.matheusmartins
  deploymentTarget:
    iOS: '15.0'

targets:
  UI:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_NAME: UI
        SWIFT_VERSION: 5.0

  UITests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: UI
    info:
      path: Tests/UITests/Info.plist
    settings:
      base:
        PRODUCT_NAME: UITests