name: TVSeriesApp
options:
  bundleIdPrefix: com.matheusmartins
  deploymentTarget:
    iOS: '15.0'

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: 5.0

projectReferences:
  Networking:
    path: Modules/Networking/Networking.xcodeproj
  UI:
    path: Modules/UI/UI.xcodeproj

targets:
  TVSeriesApp:
    type: application
    platform: iOS
    sources:
      - path: App/Sources
    info:
      path: App/Info.plist
    dependencies:
      - target: Networking/Networking
      - target: UI/UI
    settings:
      base:
        PRODUCT_NAME: TVSeriesApp

  TVSeriesAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: App/Tests/TVSeriesAppTests
    dependencies:
      - target: TVSeriesApp
    info:
      path: App/Tests/TVSeriesAppTests/Info.plist
    settings:
      base:
        PRODUCT_NAME: TVSeriesAppTests

  TVSeriesCI:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: App/Tests/CI
    dependencies:
      - target: Networking/NetworkingTests
      - target: TVSeriesApp
    info:
      path: App/Tests/CI/Info.plist
    settings:
      base:
        PRODUCT_NAME: TVSeriesCI