name: Networking
options:
  bundleIdPrefix: com.matheusmartins
  deploymentTarget:
    iOS: '15.0'

targets:
  Networking:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_NAME: Networking
        SWIFT_VERSION: 5.0

  NetworkingTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Networking
    info:
      path: Tests/Info.plist
    settings:
      base:
        PRODUCT_NAME: NetworkingTests